# Generated by Django 3.1 on 2020-08-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('cnpj', models.CharField(max_length=60)),
                ('owner', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'establishment',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('customer', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
